services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "8000:8080" # Adjust this if your app exposes a different port

volumes:
  open-webui: