services:
  webui:
    image: ghcr.io/openllm-france/open-webui:release-1.0
    env_file:
      - /mnt/envs/.env
    volumes:
      - /mnt/open-webui-data:/app/backend/data
      
  queue:
    image: ghcr.io/openllm-france/simple-queue
    environment:
      FLASK_SESSION_DURATION: 1200
      FLASK_DRAFT_DURATION: 300
      FLASK_MAX_ACTIVE_USERS: 50
    healthcheck:
      test: [ "CMD", "curl", "-f", "--request", "POST", "http://localhost:8000/queue/idle" ]
      interval: 1s
      timeout: 60s
      retries: 3

networks:
  lucie-network:
    external: true