FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && \
    poetry install --with dev --no-interaction --no-ansi --no-root

# Installer debugpy
RUN pip install debugpy



ENTRYPOINT ["poetry", "run"]
CMD ["uvicorn", "${APP_MODULE:-app.main:app}", "--host", "0.0.0.0", "--port", "8000", "--reload"] 