include :
  - authentik/docker-compose.yaml
services:
  webui:
    container_name: webui-dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - open-webui-dev:/app/backend/data
      - ./backend/open_webui:/app/backend/open_webui
    ports:
      - "8080:8080" # Adjust this if your app exposes a different port
      - "5678:5678"   # Debugger

    depends_on:
      server : 
        condition: service_healthy

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-dev
    ports:
      - "4000:4000"
    volumes:
      - ./litellm/litellm-config.yaml:/app/config.yaml
    env_file:
      - .env
    command: >
      --config /app/config.yaml
      --port 4000
      --num_workers 8
      --detailed_debug
    
    depends_on:
      - postgres  # Ensure the PostgreSQL service is started before litellm


  postgres:
    container_name: postgres-dev
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: keys_db
    volumes:
      - ./litellm/postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  open-webui1: