[tool.poetry]
name = "queue-system"
version = "0.1.0"
description = "Système de file d'attente avec FastAPI et Redis"
authors = ["Your Name <your.email@example.com>"]
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.104.1"
redis = "^5.0.1"
celery = "^5.3.6"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
asyncio = "^3.4.3"
click = "^8.1.7"
pytest-timeout = "^2.3.1"
websockets = "^12.0"
debugpy = "^1.8.11"
aioredis = "^2.0.1"
setuptools = "^75.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
pytest-cov = "^4.1.0"
httpx = "^0.25.1"
black = "^23.11.0"
isort = "^5.12.0"
flake8 = "^6.1.0"

[tool.poetry.scripts]
dev = "scripts.dev:cli"
test = "scripts.test:cli"
format = "scripts.format:cli"
readme = "scripts.update_readme:cli"
docs = "scripts.update_docs:cli"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"] 